name: Android Build CI

on:
  pull_request:

jobs:
  test:
    name: Configure OS
    runs-on: macos-latest
    #    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit tests
        run: bash ./gradlew test --stacktrace

